#!/usr/bin/env bash
PORT=${1:-3333}
if [ ! $(uname -s) = 'Darwin' ]; then
	if grep -q Microsoft /proc/version; then
		# Ubuntu on Windows using the Linux subsystem
		alias open='explorer.exe';
	else
		alias open='xdg-open';
	fi
fi
cargo install --path . --root .;
./bin/gnostr-gnit-web -d .gnostr/web/$PORT -b 127.0.0.1:$PORT -s . & \
open http://localhost:$PORT
