#!/usr/bin/env bash
PORT=${1:-8080}
if [ ! $(uname -s) = 'Darwin' ]; then
	if grep -q Microsoft /proc/version; then
		# Ubuntu on Windows using the Linux subsystem
		alias open='explorer.exe';
	else
		alias open='xdg-open';
	fi
fi
cargo install --path . --root .;
./bin/rgit -d .gnostr/web 127.0.0.1:$PORT . & \
open http://localhost:$PORT
